version: "3.4"

services:
  docker-with-node:
    build: .
    ports:
      - 5000:5000
      - 3000:3000
    volumes:
      - ./:/app
      - app/node_modules
    env_file:
      - ./.env
    # environment:
    #   NODE_ENV: production
